title: Jooing
email: kjh960215@gmail.com
description: jooing log
author: Juhye-Kim
baseurl: ""
url: "https://Juhye-Kim.github.io"

# Social Profiles
github_username: Juhye-Kim
instagram_username:
rocket_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
